### ISSUE TITLE
Wordpress Critical Error after Activating Plugin

### ISSUE THREAD

**Issue by cahlenlee** [lbryio/lbrypress#26]
**DESCRIPTION:**
After installing LBRYPress on my self-hosted Wordpress site (cahlen.org) and activating the plugin, the Wordpress /wp-admin URL shows a critical error.  I cannot access the Plugins menu to deactivate LBRYPress, and must do so via SFTP.

This may be related to the fact that I have not yet installed LBRY on the server, or created any account information. 

**REPRO STEPS:**
1) Log into self-hosted Wordpress site
2) Navigate to 'Plugins > Add New > Upload Plugin'
3) Upload 'lbrypress-master.zip'
4) Click 'Activate Plugin'

**Results:** Wordpress critical error and no access to /wp-admin

**Expected:** User is returned to Plugins menu

**ENVIRONMENT**:
WordPress version 5.3.3
Current theme: Lodestar (version 1.0.8)
Current plugin: LBRYPress (version 0.0.1)
PHP version 7.2.24-0ubuntu0.18.04.4

Error Details
=============
An error of type E_ERROR was caused in line 221 of the file /var/www/html/wp-content/plugins/lbrypress-master/classes/LBRY_Daemon.php. Error message: Uncaught Error: Call to undefined function curl_init() in /var/www/html/wp-content/plugins/lbrypress-master/classes/LBRY_Daemon.php:221
Stack trace:
#0 /var/www/html/wp-content/plugins/lbrypress-master/classes/LBRY_Daemon.php(79): LBRY_Daemon->request('account_balance')
#1 /var/www/html/wp-content/plugins/lbrypress-master/classes/LBRY_Admin.php(279): LBRY_Daemon->wallet_balance()
#2 /var/www/html/wp-includes/class-wp-hook.php(288): LBRY_Admin->wallet_balance_warning('')
#3 /var/www/html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#4 /var/www/html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#5 /var/www/html/wp-admin/admin.php(170): do_action('admin_init')
#6 /var/www/html/wp-admin/plugins.php(10): require_once('/var/www/html/w...')
#7 {main}
  thrown

![LBRYPress_0 1 1_WordpressCriticalError](https://user-images.githubusercontent.com/30788194/82733652-806e5100-9cd2-11ea-8106-72df5c569718.png)

**LBRY ADDRESS:**
baKNxWTWXaiiqJcR3Etvi9jLwiQmbWnvYc
mail@cahlen.org

**Comment by cahlenlee** [comment]
This does not occur on another self-hosted Wordpress server I have (moderndaywizards.org).  It's using the same theme as the other site, so it's not that.  Here are the versions the server that works is using:

Wordpress 5.4.1
PHP 7.2.24
Ubuntu 18.04.4
